server:
  port: ${PORT:0}
spring:
  profiles:
    active: compose
  application:
    name: bzn-gai-services-identity
  security:
    user:
      name: COMPOSE_57LPLZT907
      password: F576CDLNSN 
  # DB CONFIGURATION  
  datasource:
    url: jdbc:h2:mem:bza
    driver-class-name: org.h2.Driver
    password: sa
    username: sa
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update 
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  file:
    path: /src/main/resources/log
    name: /src/main/resources/log/${spring.application.name}.log
    max-size: 10MB
    max-history: 10
    pattern:
      console: '%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n'

  #level: ERROR, WARN, INFO, DEBUG E TRACE    
  level:
    root: WARN
    org:
      hibernate: WARN
      springframework:
        security: WARN
    br:
      brazona:
        bzn-gai-services-user:
          api: TRACE
eureka:
  instance:
    # hostname: compose
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${EUREKA_SERVER_HOST}:8761/eureka
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8762/eureka

springdoc:
  api-docs:
    path: /gai-identify/api-docs
  swagger-ui:
    path: /swagger-ui.html
    csrf:
      enabled: true